# Generated by Django 5.1.1 on 2024-10-14 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='Maximum 50 characters.', validators=[django.core.validators.MaxLengthValidator(50)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Maximum 30 characters.', max_length=30, validators=[django.core.validators.MaxLengthValidator(30)]),
        ),
    ]
