# Generated by Django 5.1.1 on 2024-10-14 19:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_post_content_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='Maximum 250 characters.', validators=[django.core.validators.MaxLengthValidator(250)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Maximum 50 characters.', max_length=50, validators=[django.core.validators.MaxLengthValidator(50)]),
        ),
    ]
