# Generated by Django 5.1.1 on 2024-10-14 19:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='Maximum 250 characters.', validators=[django.core.validators.MaxLengthValidator(250)]),
        ),
    ]
