# Generated by Django 5.1.1 on 2024-10-15 17:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_alter_post_content_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Maximum 30 characters.', max_length=30, validators=[django.core.validators.MaxLengthValidator(30)]),
        ),
    ]
