# Generated by Django 5.1.1 on 2024-10-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Maximum 20 characters.', max_length=25),
        ),
    ]
